### ISSUE TITLE
The example code isn't compiling on my M1 MacBook. Errors in the description.

### ISSUE THREAD

**Issue by MikeGitIt** [dankamongmen/notcurses-rs#5]
I am running the following toolchain:
stable-aarch64-apple-darwin
nightly-aarch64-apple-darwin (default)

I get the following details, or at least what I consider the most pertinent details, when I run a full backtrace:

`error: failed to run custom build command for `libnotcurses-sys v3.10.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/mikjagger/Documents/rust-projects/tui_client/target/debug/build/libnotcurses-sys-e092772748b38af4/build-script-build` (exit status: 101)
  
  --- stderr
  thread 'main' panicked at /Users/mikjagger/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.66/src/fallback.rs:774:9:
  "wait_struct_(unnamed_at_/Applications/Xcode_app/Contents/Developer/Platforms/MacOSX_platform/Developer/SDKs/MacOSX_sdk/usr/include/sys/wait_h_199_2)" is not a valid Ident
  stack backtrace:
     0:        0x102699d98 - std::backtrace_rs::backtrace::libunwind::trace::hc77b41cbba42bdd6
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
     1:        0x102699d98 - std::backtrace_rs::backtrace::trace_unsynchronized::h1709253e718f0f9a
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x102699d98 - std::sys_common::backtrace::_print_fmt::hc1d64a93095d6b32
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/sys_common/backtrace.rs:68:5
     3:        0x102699d98 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbc57ab87a950ad03
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/sys_common/backtrace.rs:44:22
     4:        0x1026b7bac - core::fmt::rt::Argument::fmt::hfc02f8d4a8028687
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/fmt/rt.rs:142:9
     5:        0x1026b7bac - core::fmt::write::h758d2c4d2754f689
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/fmt/mod.rs:1120:17
     6:        0x1026975c4 - std::io::Write::write_fmt::h716f6a0a441e0cf7
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/io/mod.rs:1810:15
     7:        0x102699bcc - std::sys_common::backtrace::_print::hc2b3a7c08a055b2f
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/sys_common/backtrace.rs:47:5
     8:        0x102699bcc - std::sys_common::backtrace::print::h6c92f4c3f3c139ea
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/sys_common/backtrace.rs:34:9
     9:        0x10269b374 - std::panicking::default_hook::{{closure}}::h603695a2c41940c1
    10:        0x10269b0bc - std::panicking::default_hook::h26b5c8b55b00283e
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:292:9
    11:        0x10269b7bc - std::panicking::rust_panic_with_hook::h0fe5ac1f5739994c
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:779:13
    12:        0x10269b6b0 - std::panicking::begin_panic_handler::{{closure}}::hd7de0881440ffb23
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:657:13
    13:        0x10269a21c - std::sys_common::backtrace::__rust_end_short_backtrace::h51db70a3879d8ab7
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/sys_common/backtrace.rs:171:18
    14:        0x10269b438 - rust_begin_unwind
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:645:5
    15:        0x1026cb694 - core::panicking::panic_fmt::h44d437bd0203ac62
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/panicking.rs:72:14
    16:        0x10265d6c8 - proc_macro2::fallback::validate_ident::h7d33e3de6ff59174
    17:        0x10265d4bc - proc_macro2::fallback::Ident::_new::he5c0de582acfef68
    18:        0x10265d510 - proc_macro2::fallback::Ident::new::h35c9a89a4ad8c416
    19:        0x10265f6bc - proc_macro2::imp::Ident::new::h317a070d86ed5f93
    20:        0x10266cc24 - proc_macro2::Ident::new::h459fff8c9302ff1f
    21:        0x1023bdc10 - bindgen::ir::context::BindgenContext::rust_ident_raw::ha12a29d0835b2941
    22:        0x1023bd98c - bindgen::ir::context::BindgenContext::rust_ident::h234b612c5374974c
    23:        0x1023fd130 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::h9c7c8c25783eadd8
    24:        0x102456638 - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::h1d857bb1dea56b5e
    25:        0x10243ea68 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hef7a50391b80b5b0
    26:        0x102402604 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::h9c7c8c25783eadd8
    27:        0x102456638 - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::h1d857bb1dea56b5e
    28:        0x10243ea68 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hef7a50391b80b5b0
    29:        0x102427134 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}::h66835bfd66e199c7
    30:        0x102455f40 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::h82a29ce741cb9af9
    31:        0x10243ea50 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hef7a50391b80b5b0
    32:        0x10243258c - bindgen::codegen::codegen::{{closure}}::h56db844345cb8886
    33:        0x1023bf670 - bindgen::ir::context::BindgenContext::gen::h115479c3165d6429
    34:        0x102431ffc - bindgen::codegen::codegen::h967c47cf8a27dd3b
    35:        0x1023f1d7c - bindgen::Bindings::generate::hff4e4f3541fa887a
    36:        0x1023efd94 - bindgen::Builder::generate::h7dadf50e46bee803
    37:        0x1023216f4 - build_script_build::main::h8c5dc31be78c496d
    38:        0x10231c200 - core::ops::function::FnOnce::call_once::h570ce2a7a52235fb
    39:        0x10231aed8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h061f0ac5201dc815
    40:        0x10231b7d0 - std::rt::lang_start::{{closure}}::h3e82357c9203b1aa
    41:        0x1026931b8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h313a92f94d05bb84
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/ops/function.rs:284:13
    42:        0x1026931b8 - std::panicking::try::do_call::h6ef8477516b66224
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:552:40
    43:        0x1026931b8 - std::panicking::try::hc4a2a0d148276ff2
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:516:19
    44:        0x1026931b8 - std::panic::catch_unwind::hfbd72a9a666136a0
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panic.rs:142:14
    45:        0x1026931b8 - std::rt::lang_start_internal::{{closure}}::h7b8f20312f947bab
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/rt.rs:148:48
    46:        0x1026931b8 - std::panicking::try::do_call::h8f0a190d34300167
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:552:40
    47:        0x1026931b8 - std::panicking::try::he1e6d7b58d700211
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:516:19
    48:        0x1026931b8 - std::panic::catch_unwind::h2c0a702fba11f5f9
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panic.rs:142:14
    49:        0x1026931b8 - std::rt::lang_start_internal::h2797f0933b60f3a8
                                 at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/rt.rs:148:20
    50:        0x10231b7a8 - std::rt::lang_start::he31f7b29b8c2dae4
    51:        0x102321e60 - _main`

**Comment by joseluis** [comment]
Hey @MikeGitIt sorry for the delay, are you having the same problem with the latest release?
